# Generated by Django 4.2.15 on 2024-09-05 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='book_media')),
                ('age', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('education', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_experience', models.TextField()),
                ('skills', models.CharField(max_length=200)),
                ('cerifications', models.TextField()),
                ('first_Project_Title', models.CharField(max_length=200)),
                ('first_Project_Description', models.TextField()),
                ('first_Project_Image', models.ImageField(upload_to='book_media')),
                ('first_Project_Link', models.URLField()),
                ('second_Project_Title', models.CharField(max_length=200)),
                ('second_Project_Description', models.TextField()),
                ('second_Project_Image', models.ImageField(upload_to='book_media')),
                ('second_Project_Link', models.URLField()),
                ('third_Project_Title', models.CharField(max_length=200)),
                ('third_Project_Description', models.TextField()),
                ('third_Project_Image', models.ImageField(upload_to='book_media')),
                ('third_Project_Link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userprofile')),
            ],
        ),
    ]
