# Generated by Django 4.2.15 on 2024-09-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_userprofile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='book_media'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='cerifications',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='first_Project_Description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='first_Project_Image',
            field=models.ImageField(null=True, upload_to='book_media'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='first_Project_Link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='first_Project_Title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='second_Project_Description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='second_Project_Image',
            field=models.ImageField(null=True, upload_to='book_media'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='second_Project_Link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='second_Project_Title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='skills',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='third_Project_Description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='third_Project_Image',
            field=models.ImageField(null=True, upload_to='book_media'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='third_Project_Link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='third_Project_Title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='work_experience',
            field=models.TextField(null=True),
        ),
    ]
